version: "3"

services:
  es:
      image: elasticsearch:8.5.2
      environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - ./data:/usr/share/elasticsearch/data
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
        - es

  kibana:
    image: kibana:8.5.2
    volumes:
      - ./kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - es

networks:
  es:
