version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "8090:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: alice
      PASSWORD: secret1234
    volumes:
      - ./data:/var/lib/dav
